# Generated by Django 4.1 on 2023-03-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('private_key', models.CharField(blank=True, max_length=255, null=True)),
                ('public_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BinanceAccount',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('private_key', models.CharField(blank=True, max_length=255, null=True)),
                ('public_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'binance_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code_iso', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'currency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('os_version', models.CharField(blank=True, max_length=255, null=True)),
                ('lang', models.CharField(blank=True, max_length=255, null=True)),
                ('os_name', models.CharField(blank=True, max_length=255, null=True)),
                ('device_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, max_length=255, null=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('device_model', models.CharField(blank=True, max_length=255, null=True)),
                ('app_version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoctrineMigrationVersions',
            fields=[
                ('version', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doctrine_migration_versions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'exchange',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MessengerMessages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('headers', models.TextField()),
                ('queue_name', models.CharField(max_length=190)),
                ('created_at', models.DateTimeField()),
                ('available_at', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messenger_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('refresh_token', models.CharField(max_length=128, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('valid', models.DateTimeField()),
            ],
            options={
                'db_table': 'refresh_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'symbol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(max_length=255)),
                ('order_direction', models.CharField(max_length=255)),
                ('fees', models.FloatField()),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('external_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('quantity', models.FloatField()),
                ('fees', models.FloatField(blank=True, null=True)),
                ('external_transfer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'transfer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=180, unique=True)),
                ('roles', models.TextField()),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('plain_password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetExchange',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.asset')),
            ],
            options={
                'db_table': 'asset_exchange',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SymbolExchange',
            fields=[
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.symbol')),
            ],
            options={
                'db_table': 'symbol_exchange',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('date', models.DateTimeField()),
                ('average_purchase_price', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.asset')),
            ],
            options={
                'db_table': 'holding',
            },
        ),
    ]
