# Generated by Django 4.1 on 2023-03-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetprices',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
    ]
