# Generated by Django 4.1 on 2023-03-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='return_on_investment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
