# Generated by Django 4.1 on 2023-03-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_holding_return_on_investment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='average_purchase_price',
        ),
    ]
