# Generated by Django 4.1 on 2023-03-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_assetprices_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAssetReturn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('return_on_investment', models.FloatField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.asset')),
            ],
            options={
                'db_table': 'account_asset_return',
            },
        ),
    ]
